<a href="https://colab.research.google.com/github/Sayed-Hossein-Hosseini/A_Journey_into_the_Depths_of_Neural_Networks/blob/master/Diversity_of_Networks_and_Optimizers_for_Progress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Diversity of Networks and Optimizers for Progress**

## **Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
import torch
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, precision_score, recall_score

## **Loading Dataset and Normalization**

In [2]:
if __name__ == "__main__":
    # Load in the data
    cifar10 = tf.keras.datasets.cifar10

    (X_train, y_train), (X_test, y_test) = cifar10.load_data()
    X_train, X_test = X_train / 255.0, X_test / 255.0

    print(X_train.shape)
    print(X_test.shape)

    print(y_train.shape)
    print(y_test.shape)

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
(50000, 32, 32, 3)
(10000, 32, 32, 3)
(50000, 1)
(10000, 1)


## **Flatten and Reshape Images**

In [3]:
if __name__ == "__main__":
    # reshape images from (32, 32, 3) to (3072,)
    X_train = X_train.reshape((X_train.shape[0], -1))  # (50000, 3072)
    X_test = X_test.reshape((X_test.shape[0], -1))     # (10000, 3072)

    y_train, y_test = y_train.flatten(), y_test.flatten() # (50000,  -   10000,)
    print(y_train[:10])

[6 9 9 4 1 1 2 7 8 3]


## **One-Hot Encoding**

In [4]:
y_train = to_categorical(y_train, num_classes=10)
# y_test = to_categorical(y_test, num_classes=10)

print(y_train.shape)
# print(y_test.shape)

print(y_train[:10])
# print(y_test[:10])

(50000, 10)
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


## **Model**

### **Activation Function : Sigmoid and Relu and Softmax and Tanh**

In [ ]:
class Activation:
    @staticmethod
    def sigmoid(z):
        return 1 / (1 + np.exp(-z))

    @staticmethod
    def sigmoid_derivative(a):
        return a * (1 - a)

    @staticmethod
    def relu(z):
        return np.maximum(0, z)

    @staticmethod
    def relu_derivative(z):
        return (z > 0).astype(float)

    @staticmethod
    def softmax(z):
        exps = np.exp(z - np.max(z, axis=1, keepdims=True))  # For numerical stability
        return exps / np.sum(exps, axis=1, keepdims=True)

    @staticmethod
    def softmax_derivative(output):
        # The exact derivative of softmax is a Jacobian matrix.
        # However, when used with cross-entropy loss, the gradient simplifies to:
        # ∂L/∂z = y_pred - y_true
        # So this method is typically not needed explicitly during backpropagation.
        pass

    @staticmethod
    def tanh(z):
        return np.tanh(z)

    @staticmethod
    def tanh_derivative(a):
        return 1 - np.power(a, 2)

## **Neural Network**

### **Dence Layer Class**

In [ ]:
class DenseLayer:
    def __init__(self, input_size, output_size, activation='sigmoid'):
        self.w = np.random.randn(input_size, output_size) * 0.01
        self.b = np.zeros((1, output_size))
        self.activation_name = activation
        self.z = None
        self.a = None
        self.input = None
        self.dw = None
        self.db = None

    def forward(self, x):
        self.input = x
        self.z = np.dot(x, self.w) + self.b
        if self.activation_name == 'sigmoid':
            self.a = Activation.sigmoid(self.z)
        elif self.activation_name == 'relu':
            self.a = Activation.relu(self.z)
        elif self.activation_name == 'tanh':
            self.a = Activation.tanh(self.z)
        elif self.activation_name == 'softmax':
            self.a = Activation.softmax(self.z)
        else:
            raise ValueError(f"Unsupported activation function: {self.activation_name}")
        return self.a

    def backward(self, da):
        m = self.input.shape[0]
        if self.activation_name == 'sigmoid':
            dz = da * Activation.sigmoid_derivative(self.a)
        elif self.activation_name == 'relu':
            dz = da * Activation.relu_derivative(self.z)
        elif self.activation_name == 'tanh':
            dz = da * Activation.tanh_derivative(self.a)
        elif self.activation_name == 'softmax':
            dz = da  # softmax + cross-entropy
        else:
            raise ValueError(f"Unsupported activation function: {self.activation_name}")

        self.dw = np.dot(self.input.T, dz) / m
        self.db = np.sum(dz, axis=0, keepdims=True) / m
        return np.dot(dz, self.w.T)

### **Optimizer Classes**

In [ ]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr

    def update(self, layer):
        layer.w -= self.lr * layer.dw
        layer.b -= self.lr * layer.db


class Momentum:
    def __init__(self, lr=0.01, beta=0.9):
        self.lr = lr
        self.beta = beta
        self.v_w = {}
        self.v_b = {}

    def update(self, layer):
        if layer not in self.v_w:
            self.v_w[layer] = np.zeros_like(layer.w)
            self.v_b[layer] = np.zeros_like(layer.b)
        self.v_w[layer] = self.beta * self.v_w[layer] + (1 - self.beta) * layer.dw
        self.v_b[layer] = self.beta * self.v_b[layer] + (1 - self.beta) * layer.db
        layer.w -= self.lr * self.v_w[layer]
        layer.b -= self.lr * self.v_b[layer]


class Adam:
    def __init__(self, lr=0.001, beta1=0.9, beta2=0.999, epsilon=1e-8):
        self.lr = lr
        self.beta1 = beta1
        self.beta2 = beta2
        self.epsilon = epsilon
        self.m_w, self.v_w = {}, {}
        self.m_b, self.v_b = {}, {}
        self.t = {}

    def update(self, layer):
        if layer not in self.m_w:
            self.m_w[layer] = np.zeros_like(layer.w)
            self.v_w[layer] = np.zeros_like(layer.w)
            self.m_b[layer] = np.zeros_like(layer.b)
            self.v_b[layer] = np.zeros_like(layer.b)
            self.t[layer] = 0

        self.t[layer] += 1

        self.m_w[layer] = self.beta1 * self.m_w[layer] + (1 - self.beta1) * layer.dw
        self.v_w[layer] = self.beta2 * self.v_w[layer] + (1 - self.beta2) * (layer.dw ** 2)
        self.m_b[layer] = self.beta1 * self.m_b[layer] + (1 - self.beta1) * layer.db
        self.v_b[layer] = self.beta2 * self.v_b[layer] + (1 - self.beta2) * (layer.db ** 2)

        m_w_hat = self.m_w[layer] / (1 - self.beta1 ** self.t[layer])
        v_w_hat = self.v_w[layer] / (1 - self.beta2 ** self.t[layer])
        m_b_hat = self.m_b[layer] / (1 - self.beta1 ** self.t[layer])
        v_b_hat = self.v_b[layer] / (1 - self.beta2 ** self.t[layer])

        layer.w -= self.lr * m_w_hat / (np.sqrt(v_w_hat) + self.epsilon)
        layer.b -= self.lr * m_b_hat / (np.sqrt(v_b_hat) + self.epsilon)